--
-- PostgreSQL database dump
--

-- Dumped from database version 18.6 (2078fcb)
-- Dumped by pg_dump version 18.6 (2078fcb)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: neon; Type: SCHEMA; Schema: -; Owner: cloud_admin
--

CREATE SCHEMA neon;


ALTER SCHEMA neon OWNER TO cloud_admin;

--
-- Name: neon_migration; Type: SCHEMA; Schema: -; Owner: cloud_admin
--

CREATE SCHEMA neon_migration;


ALTER SCHEMA neon_migration OWNER TO cloud_admin;

--
-- Name: neon; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS neon WITH SCHEMA neon;


--
-- Name: EXTENSION neon; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION neon IS 'cloud storage for PostgreSQL';


--
-- Name: pg_stat_statements; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;


--
-- Name: EXTENSION pg_stat_statements; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pg_stat_statements IS 'track planning and execution statistics of all SQL statements executed';


--
-- Name: get_compute_primary_memory_bytes(); Type: FUNCTION; Schema: public; Owner: cloud_admin
--

CREATE FUNCTION public.get_compute_primary_memory_bytes() RETURNS bigint
    LANGUAGE plpgsql
    AS $$
DECLARE
    result BIGINT;
    flag_enabled BOOLEAN;
BEGIN
    -- Check if this is a replica (primary should never emit this metric)
    IF NOT pg_catalog.pg_is_in_recovery() THEN
        RETURN NULL;
    END IF;

    -- Check if the autoscaling state transfer flag is enabled
    -- The flag is exposed as a PostgreSQL GUC by compute_ctl
    -- Note: current_setting returns NULL if the setting doesn't exist (with missing_ok=true)
    -- We treat NULL as "flag not enabled" to be safe
    flag_enabled := pg_catalog.current_setting('neon.autoscaling_state_transfer_enabled', true) = 'on';
    IF flag_enabled IS NULL OR NOT flag_enabled THEN
        RETURN NULL;
    END IF;

    -- Get the value from the table
    SELECT (value)::bigint INTO result
    FROM public.lakebase_attributes
    WHERE name = 'primary_memory' AND value IS NOT NULL;

    -- Return NULL if no row found (COALESCE not used - we want NULL to not emit metric)
    RETURN result;
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END;
$$;


ALTER FUNCTION public.get_compute_primary_memory_bytes() OWNER TO cloud_admin;

--
-- Name: health_check_write_succeeds(); Type: FUNCTION; Schema: public; Owner: cloud_admin
--

CREATE FUNCTION public.health_check_write_succeeds() RETURNS integer
    LANGUAGE plpgsql
    AS $$
BEGIN
INSERT INTO public.health_check VALUES (1, now())
ON CONFLICT (id) DO UPDATE
    SET updated_at = now();

RETURN 1;
EXCEPTION WHEN OTHERS THEN
RAISE EXCEPTION '[NEON_SMGR] health_check failed: [%] %', SQLSTATE, SQLERRM;
RETURN 0;
END;
$$;


ALTER FUNCTION public.health_check_write_succeeds() OWNER TO cloud_admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: migration_id; Type: TABLE; Schema: neon_migration; Owner: cloud_admin
--

CREATE TABLE neon_migration.migration_id (
    key integer NOT NULL,
    id bigint DEFAULT 0 NOT NULL
);


ALTER TABLE neon_migration.migration_id OWNER TO cloud_admin;

--
-- Name: health_check; Type: TABLE; Schema: public; Owner: cloud_admin
--

CREATE TABLE public.health_check (
    id integer NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.health_check OWNER TO cloud_admin;

--
-- Name: health_check_id_seq; Type: SEQUENCE; Schema: public; Owner: cloud_admin
--

ALTER TABLE public.health_check ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_check_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lakebase_attributes; Type: TABLE; Schema: public; Owner: cloud_admin
--

CREATE TABLE public.lakebase_attributes (
    name text NOT NULL,
    value jsonb,
    last_updated timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.lakebase_attributes OWNER TO cloud_admin;

--
-- Name: migration_id migration_id_pkey; Type: CONSTRAINT; Schema: neon_migration; Owner: cloud_admin
--

ALTER TABLE ONLY neon_migration.migration_id
    ADD CONSTRAINT migration_id_pkey PRIMARY KEY (key);


--
-- Name: health_check health_check_pkey; Type: CONSTRAINT; Schema: public; Owner: cloud_admin
--

ALTER TABLE ONLY public.health_check
    ADD CONSTRAINT health_check_pkey PRIMARY KEY (id);


--
-- Name: lakebase_attributes lakebase_attributes_pkey; Type: CONSTRAINT; Schema: public; Owner: cloud_admin
--

ALTER TABLE ONLY public.lakebase_attributes
    ADD CONSTRAINT lakebase_attributes_pkey PRIMARY KEY (name);


--
-- Name: migration_id neon_migration_id_superuser_check; Type: TRIGGER; Schema: neon_migration; Owner: cloud_admin
--

CREATE TRIGGER neon_migration_id_superuser_check BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON neon_migration.migration_id FOR EACH STATEMENT EXECUTE FUNCTION neon.neon_check_for_superuser();


--
-- Name: health_check neon_health_check_superuser_check; Type: TRIGGER; Schema: public; Owner: cloud_admin
--

CREATE TRIGGER neon_health_check_superuser_check BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.health_check FOR EACH STATEMENT EXECUTE FUNCTION neon.neon_check_for_superuser();


--
-- Name: FUNCTION pg_export_snapshot(); Type: ACL; Schema: pg_catalog; Owner: cloud_admin
--

GRANT ALL ON FUNCTION pg_catalog.pg_export_snapshot() TO neon_superuser;


--
-- Name: FUNCTION pg_log_standby_snapshot(); Type: ACL; Schema: pg_catalog; Owner: cloud_admin
--

GRANT ALL ON FUNCTION pg_catalog.pg_log_standby_snapshot() TO neon_superuser;


--
-- Name: FUNCTION pg_show_replication_origin_status(OUT local_id oid, OUT external_id text, OUT remote_lsn pg_lsn, OUT local_lsn pg_lsn); Type: ACL; Schema: pg_catalog; Owner: cloud_admin
--

GRANT ALL ON FUNCTION pg_catalog.pg_show_replication_origin_status(OUT local_id oid, OUT external_id text, OUT remote_lsn pg_lsn, OUT local_lsn pg_lsn) TO neon_superuser;


--
-- PostgreSQL database dump complete
--

