# -*- coding: utf-8 -*-
"""x150: export/raw 内部活动导出对照 + hackbot/genii 触发
对"自己的 N/A 报告"测 include_internal_activities=false/true 差异
关键词过滤输出,避免刷屏"""
L = []
L.append('(async () => {')
L.append('  const sleep = ms => new Promise(r => setTimeout(r, ms));')
L.append("  const csrf = document.querySelector('meta[name=\"csrf-token\"]').content;")
L.append('  const out = [];')
L.append('  const MARK = ["internal", "triage", "analyst", "duplicate", "not applicable", "resolution", "verdict", "n/a", "reason", "note"];')
L.append('  const rid = 3972961;')
L.append('  const doRaw = async (label, inc) => {')
L.append('    const r = await fetch(`/reports/${rid}/export/raw`, {')
L.append("      method: 'POST', headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': csrf },")
L.append('      body: JSON.stringify({ include_internal_activities: inc, redact_usernames: false })')
L.append('    });')
L.append('    const t = await r.text();')
L.append('    const lines = t.split("\\n");')
L.append('    const hits = [];')
L.append('    lines.forEach((ln, i) => {')
L.append('      const low = ln.toLowerCase();')
L.append('      for (const m of MARK) { if (low.includes(m)) { hits.push("L" + i + ": " + ln.slice(0, 240)); break; } }')
L.append('    });')
L.append('    out.push(`===== RAW inc=${inc} status=${r.status} len=${t.length} lines=${lines.length}`);')
L.append('    out.push(hits.length ? hits.slice(0, 30).join("\\n") : "(no marker lines)");')
L.append('  };')
L.append("  await doRaw('RAW-false', false);")
L.append('  await sleep(500);')
L.append("  await doRaw('RAW-true', true);")
L.append('  await sleep(500);')
# hackbot/genii 触发(自己报告)
L.append('  try {')
L.append('    const r = await fetch(`/hackbot/genii?report_id=${rid}`, { headers: { "X-Requested-With": "XMLHttpRequest" } });')
L.append('    const t = await r.text();')
L.append('    out.push(`===== GENII status=${r.status} len=${t.length}\\n` + t.slice(0, 1500));')
L.append('  } catch (e) { out.push("GENII ERR " + e); }')
L.append('  const ta = document.createElement("textarea");')
L.append("  ta.style.cssText = 'position:fixed;top:0;left:0;width:97%;height:92%;z-index:999999;font:10px monospace;white-space:pre;';")
L.append("  ta.value = out.join('\\n\\n');")
L.append('  document.body.appendChild(ta); ta.focus(); ta.select();')
L.append('})();')

block = '\n'.join(L)
open('D:/scan/h1kit/_h1x150_export_block.txt', 'w', encoding='utf-8').write(block)
print('lines:', len(L))
print(block)
